VAGRANTFILE_API_VERSION = "2"

# SyncFolder on Host ist $HOME/vagrantWebDev
SYNCFOLDER_ROOT = [ENV['HOME'],"/vagrantWebDev"].join()

SYNCFOLDER_HOST_SHARE = SYNCFOLDER_ROOT + "/share"
SYNCFOLDER_GUEST_SHARE = "/home/vagrant/share"

SYNCFOLDER_HOST_WWW = SYNCFOLDER_ROOT + "/www"
SYNCFOLDER_GUEST_WWW = "/var/www"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "webDev"
  config.vm.synced_folder SYNCFOLDER_HOST_SHARE, SYNCFOLDER_GUEST_SHARE, create: true
  config.vm.synced_folder SYNCFOLDER_HOST_WWW, SYNCFOLDER_GUEST_WWW, create: true

  config.vm.provider "virtualbox" do |vb|
     # Start with Gui
     vb.gui = true
     # Set hostname
     vb.name = "webDevMachine"
  end

   # Puppet
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
    puppet.manifests_path = "../puppet/manifests"
    puppet.manifest_file  = "default.pp"
    puppet.module_path = "../puppet/modules"
  end


end
