VAGRANTFILE_API_VERSION = "2"

SYNCFOLDER_HOST = "/tmp"
SYNCFOLDER_GUEST = "/tmp"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "webDev"
  config.vm.synced_folder SYNCFOLDER_HOST, SYNCFOLDER_GUEST

  config.vm.provider "virtualbox" do |vb|
     # Start with Gui
     vb.gui = true
     # Set hostname
     vb.name = "webDevMachine"
  end

   # Puppet
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
    puppet.manifests_path = "../puppet/manifests"
    puppet.manifest_file  = "default.pp"
    puppet.module_path = "../puppet/modules"
  end


end
