# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

SYNCFOLDER_HOST = "/home/h41/tmp"
SYNCFOLDER_GUEST = "/tmp"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder SYNCFOLDER_HOST, SYNCFOLDER_GUEST
  # Enable GUI
#  config.vm.provider "virtualbox" do |vb|
#	vb.gui = true
#  end
end
